name: Feature request
description: Suggest a new feature or enhancement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What problem are we solving?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Bullet list of "done means" checks.
  - type: textarea
    id: artifacts
    attributes:
      label: Artifacts
      description: What evidence/doc changes should accompany this?